### ISSUE TITLE
How can we help ? 

### ISSUE THREAD

**Issue by jgaNet** [elisa-tech/workgroups#1]
Hi,
My name is Jeremy. I'm interresting by your project but I don't know how to start. I'm architect software developer and I can help to create some tools. I use Linux everyday in my work  (Ubuntu, Debian, Raspbian, etc...) and i would like to participate. I know tools as Kubernetes, Docker, Gitlab with cluster deployments inside linux environments (embedded devices or cloud), some services as SQL or NoSQL Databases (postgreSQL, MongoDb, InfluxDb, Redis, DynamoDb, ...), Real time TCP protocols as HTTP, Nats, WebSockets, MQTT and programming languages as JavaScript, Ruby  and C++. Often I like to test new technologies as blockchain, IOT system or ML tools.

Can I help ? 

Thank you

**Comment by bulwahn** [comment]
Hi @jgaNet, you can find some basic project ideas here: https://wiki.linuxfoundation.org/gsoc/2019-gsoc-safety-critical-linux
The project proposal are for students, but there are some more complex tasks around those areas described there as well. Let me know which area is of interest for you.
I think there are three interesting tasks for you given your background:
1. Integrating the patch stack analysis (pasta) into the patchwork tool
2. Extending the elixir web interface to show code issues identified with static analysis tools
3. Creating a web interface for tracking tool analysis findings over time
Let me know what you consider interesting and then I can explain in more detail, introduce you to the general problem and work out the details together.

**Comment by bulwahn** [comment]
You can also find our mailing list here:

https://lists.elisa.tech/topics

**Comment by pahmann** [comment]
@bulwahn should we close this issue? I guess no further action is needed here.

**Comment by bulwahn** [comment]
@pahmann I agree and I will close this issue.
@jgaNet I provided you the pointers to the discussion forum and some ideas for implementation tasks. If you are interested, be just reach out to me by email or on the elisa devel mailing list.

**Comment by pahmann** [comment]
@jgaNet in case you feel your question is answered, feel free to close this issue. (Normally the reporter has the right to do it.)
If you need some first support. Join our regular call or drop a mail via mailinglist. Details can be found here https://lists.elisa.tech/topics as stated by Lukas.

**Comment by pahmann** [comment]
Closed during issue clean up after TSC chair change.
