### ISSUE TITLE
Create gold deck for the problem and need ELISA addresses

### ISSUE THREAD

**Issue by bulwahn** [elisa-tech/workgroups#12]
Gold deck to use to explain the problem and need for participants:
  - Pain problems
  - Use Cases for ELISA - medical equipment, industry automation,  autonomous systems (vehicle, factories, robots).   
  - Why use linux - new technologies available quicker,  no licensing fees, total cost over lifecycle.   
  - Wider community to draw on for security issues.  ELISA is build a wider community focused on safety issues.

  - [x] Kate to take first pass - next Tuesday.
  - [ ] Nicole, Nicholas, Olaf to review Wed/Thurs.

**Comment by kestewart** [comment]
Starting point is at: [https://docs.google.com/presentation/d/1m62n5A2229Kxkt7hGD5aYFAj5Ara_WG1NlnDy8MP7c8](https://docs.google.com/presentation/d/1m62n5A2229Kxkt7hGD5aYFAj5Ara_WG1NlnDy8MP7c8)

Need to add some of the basic Use Cases for ELISA & Linux to the start, but hopefully the rest is reasonable.   Just ask if you want edit access to it,  everyone can comment at this point.

**Comment by bulwahn** [comment]
My mobile device does not allow me to comment on the slides, so just a quick important pointer here. On slide 14, you wrongly attributed the autonomous driving use case to SIL2LinuxMP, but it is done in trustable.io and more specifically is mainly driven by Codethink. More comments will follow when back in the office.

**Comment by pahmann** [comment]
Gold deck presented during OSS EU in Dublin. It has the latest version of the gold deck.
