### ISSUE TITLE
Enable ambassadors for the project to speak at conferences/events/in-house/executives 

### ISSUE THREAD

**Issue by bulwahn** [elisa-tech/workgroups#14]
Create information material to help ambassadors (reference material online, including slides to walk through, whitepapers for offline reading)

  - [x] Nicole: Outreach to Bitkom Forum:  Nicole to provide overview at next working group meeting. 
  - [x] Nicole: Provide feedback to Kate on Gold Deck

**Comment by pahmann** [comment]
Ambassadors established.
