### ISSUE TITLE
Collect list of tools & libraries for qualification

### ISSUE THREAD

**Issue by bulwahn** [elisa-tech/workgroups#15]
Collect from the case studies or from a common understanding how certain tools are used in the kernel development process, i.e., kernel documentation.

**Comment by slotosch** [comment]
Thank you for creating the issue.

Helping information: https://www.kernel.org/doc/html/latest/admin-guide/README.html 
I will take care, ideally with the imputs from the SIL2LinuxMP-Project

**Comment by pahmann** [comment]
@bulwahn and @slotosch should we close this issue as not planned? 

In case you have some links to add here as documentation of the work, please add these here.

**Comment by slotosch** [comment]
Yes, please close this. We can postpone the activity until there is usage within a project.
