### ISSUE TITLE
Setup further means of exchange and communication

### ISSUE THREAD

**Issue by bulwahn** [elisa-tech/workgroups#3]
On the first workshop, we discussed:
- [x] Organise Weekly Sync, Thursday 15:00 - 16:00 CEST: intended as open hangout for participants
- [ ] Set up of a Flock channel (asked Min on 2019-06-26 11:20 CEST for support)

**Comment by pahmann** [comment]
Flock channel not estasblished.
Weekly meeting formalized.
Closing this issue as part of cleanup during TSC chair takeover.
