### ISSUE TITLE
CG: Unify build log format

### ISSUE THREAD

**Issue by m5imunovic** [elisa-tech/workgroups#51]
Currently, the callgraph-tool accepts various input formats for creating the callgraph database from the compilation logs. Modify the tool to accept exclusively format defined with http://clang.llvm.org/docs/JSONCompilationDatabase.html.
For the existing formats that use raw buildlog create a tool script that will convert it to JSON compilation database.
Note: LL_CLANG format accepts build dir and is not affected by this change.

**Comment by henrirosten** [comment]
@m5imunovic : can we close this issue as not relevant?

**Comment by m5imunovic** [comment]
Closing it as non-relevant
