### ISSUE TITLE
CG: Rewrite the parsing engine relying on the Clang LibTooling

### ISSUE THREAD

**Issue by m5imunovic** [elisa-tech/workgroups#52]
The parser is implemented with hand-crafted patterns that might break as clang IR format is evolving. Rely on the Clang/LLVM codebase to parse out the IR relevant data. Rewrite current IR parser C++ back-end and supporting build files.

**Comment by henrirosten** [comment]
@m5imunovic : can we close this issue as not relevant?

**Comment by m5imunovic** [comment]
Closing as non-relevant.
