### ISSUE TITLE
CG: Establish callgraph tool indexer as kbuild make target

### ISSUE THREAD

**Issue by m5imunovic** [elisa-tech/workgroups#53]
Possibibly Very Difficult: The callgraph database for Linux source tree is built as a post processing step of the kbuild process. Establish the indexer build process as a Kbuild target inside of the Linux OS community.

**Comment by henrirosten** [comment]
@m5imunovic : can we close this issue as not relevant?

**Comment by m5imunovic** [comment]
Closing as non-relevant.
