### ISSUE TITLE
CG: Implement better mechanism for unique node identification

### ISSUE THREAD

**Issue by m5imunovic** [elisa-tech/workgroups#55]
Currently the callgraph is only relying on function name as identificator, which works the most time but results in the callgraph database errors occassionaly. If there are functions with the same name only the first one detected ends up in the database. As the processing is done in a multithreaded fashion the results will differ from run to run.

**Comment by henrirosten** [comment]
@m5imunovic : can we close this issue as not relevant?

**Comment by m5imunovic** [comment]
Close as non-relevant.
