### ISSUE TITLE
Obtain information on relevant reference system profiles

### ISSUE THREAD

**Issue by bulwahn** [elisa-tech/workgroups#8]
Looking for input from Kuka, BMW, Toyota: Are there profiles?

 - [ ] Kuka: Stefan S. will look at examples here to provide
 - [ ] BMW: Lukas will look for
 - [ ] Toyota: Ando will look for.

Call a meeting when material available, and then look and seeing what is possible.

Oscar will volunteer to look at tools and libraries and comment on them.

**Comment by pahmann** [comment]
Reviewed during taking over as new TSC chair. Closing this issue unresovled as outdated.
